services:
  desktop:
    image: lscr.io/linuxserver/webtop:debian-xfce
    container_name: desktop

    privileged: false

    environment:
      - TZ=Asia/Kolkata
      - PUID=1000
      - PGID=1000

      - CUSTOM_USER=admin
      - PASSWORD=123
      - TITLE=Web Desktop

    ports:
      - "6080:3000"

    volumes:
      - ./config:/config

    shm_size: "4gb"

    # SAFE performance limits (works almost everywhere)
    cpus: 4
    mem_limit: 12g

    ulimits:
      nofile:
        soft: 65535
        hard: 65535

    devices:
      - /dev/dri:/dev/dri

    security_opt:
      - no-new-privileges:true

    restart: unless-stopped